version: '2'

#
services:
  #
  # MySQL
  database:
    build:
      context: server-db
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: restapi
      MYSQL_DATABASE: restapi
    ports:
      - 3306:3306
#    network_mode: "bridge"


  apiserverdocker:
    build:
      context: server-api
    image: miksonx/server-api:latest
    container_name: server-api
    ports:
      - "5050:5050"
    restart: always
#    network_mode: "bridge"



  reactapi:
    build:
      context: react-api
    image: miksonx/react-api:latest
    container_name: react-api
    ports:
      - "3030:3030"
    restart: always
#    network_mode: "bridge"


  #
  # Selenium Chrome
  #
  # seleniumchrome:
  #   depends_on:
  #     - apiserverdocker
  #   links:
  #     - apiserverdocker
  #   image: selenium/standalone-chrome-debug:3.12
  #   container_name: seleniumchrome
  #   ports:
  #     - "4444:4444"
  #     - "5800:5900"
  #   restart: always
#    network_mode: "bridge"