DROP DATABASE IF EXISTS `restapi`;
CREATE DATABASE IF NOT EXISTS `restapi` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `restapi`;
CREATE TABLE blog (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  content VARCHAR(5000) NOT NULL
);
